title: Xuan-Bach Le
url: "https://lexuanbach.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/lexuanbach"
footer_text: "A website for both personal and professional purposes"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/xuanbach/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
